name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - "**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: .

      - name: Deploy to AWS
        env:
          AWS_HOST: ${{ secrets.AWS_HOST }}
          AWS_USER: ${{ secrets.AWS_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Set up SSH private key
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Disable host key checking for SSH
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          
          # Deploy to AWS
          ssh -i ~/.ssh/id_rsa $AWS_USER@$AWS_HOST << 'EOF'
          cd /home/ubuntu/Task_Management_API
          
          git pull

          docker compose down
          docker compose pull
          docker compose --profile production build
          docker compose --profile production up -d

          EOF